# Generated by Django 5.0.14 on 2025-12-22 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Культура')),
                ('variety', models.CharField(blank=True, max_length=128, verbose_name='Сорт')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Овощная культура',
                'verbose_name_plural': 'Овощные культуры',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CropCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Начало цикла')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Окончание цикла')),
                ('status', models.CharField(choices=[('planned', 'Запланирован'), ('active', 'В работе'), ('finished', 'Завершён'), ('canceled', 'Отменён')], default='planned', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Цикл выращивания',
                'verbose_name_plural': 'Циклы выращивания',
                'ordering': ('-start_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='CropSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sow_start', models.DateField(blank=True, null=True, verbose_name='Посев: начало')),
                ('sow_end', models.DateField(blank=True, null=True, verbose_name='Посев: окончание')),
                ('watering_start', models.DateField(blank=True, null=True, verbose_name='Полив: начало')),
                ('watering_end', models.DateField(blank=True, null=True, verbose_name='Полив: окончание')),
                ('watering_interval_days', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Полив: интервал (дней)')),
                ('fertilizing_start', models.DateField(blank=True, null=True, verbose_name='Удобрения: начало')),
                ('fertilizing_end', models.DateField(blank=True, null=True, verbose_name='Удобрения: окончание')),
                ('fertilizing_interval_days', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Удобрения: интервал (дней)')),
                ('harvest_start', models.DateField(blank=True, null=True, verbose_name='Сбор: начало')),
                ('harvest_end', models.DateField(blank=True, null=True, verbose_name='Сбор: окончание')),
            ],
            options={
                'verbose_name': 'График культуры',
                'verbose_name_plural': 'Графики культур',
            },
        ),
        migrations.CreateModel(
            name='Greenteplitsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название')),
                ('greenteplitsa_type', models.CharField(choices=[('vegetables', 'Овощи'), ('greens', 'Зель'), ('berries', 'Ягоды'), ('other', 'Другое')], default='vegetables', max_length=32, verbose_name='Тип продукции')),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Площадь, м²')),
                ('location', models.CharField(blank=True, max_length=128, verbose_name='Расположение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Теплица',
                'verbose_name_plural': 'Теплицы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_date', models.DateField(verbose_name='Фактическая дата')),
                ('water_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Вода, л')),
                ('fertilizer_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Удобрения, кг')),
                ('labor_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Трудозатраты, ч')),
                ('yield_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Урожай, кг')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Факт работ',
                'verbose_name_plural': 'Факты работ',
                'ordering': ('-actual_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='WorkPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date', models.DateField(verbose_name='Плановая дата')),
                ('planned_end_date', models.DateField(blank=True, null=True, verbose_name='Плановое окончание')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'План работ',
                'verbose_name_plural': 'Планы работ',
                'ordering': ('planned_date', 'id'),
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип работы',
                'verbose_name_plural': 'Типы работ',
                'ordering': ('name',),
            },
        ),
        migrations.AddConstraint(
            model_name='crop',
            constraint=models.UniqueConstraint(fields=('name', 'variety'), name='uniq_crop_name_variety'),
        ),
        migrations.AddField(
            model_name='cropcycle',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_cycles', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал'),
        ),
        migrations.AddField(
            model_name='cropcycle',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycles', to='greenteplitsa.crop', verbose_name='Культура'),
        ),
        migrations.AddField(
            model_name='cropschedule',
            name='crop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='greenteplitsa.crop', verbose_name='Культура'),
        ),
        migrations.AddField(
            model_name='cropcycle',
            name='greenteplitsa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycles', to='greenteplitsa.greenteplitsa', verbose_name='Теплица'),
        ),
        migrations.AddField(
            model_name='worklog',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_worklogs', to=settings.AUTH_USER_MODEL, verbose_name='Кто внёс'),
        ),
        migrations.AddField(
            model_name='worklog',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='greenteplitsa.cropcycle', verbose_name='Цикл'),
        ),
        migrations.AddField(
            model_name='workplan',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='greenteplitsa.cropcycle', verbose_name='Цикл'),
        ),
        migrations.AddField(
            model_name='worklog',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='greenteplitsa.workplan', verbose_name='План'),
        ),
        migrations.AddField(
            model_name='workplan',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='greenteplitsa.worktype', verbose_name='Тип работы'),
        ),
        migrations.AddField(
            model_name='worklog',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='greenteplitsa.worktype', verbose_name='Тип работы'),
        ),
    ]
